export const projects = [
    {
      src: "./images/newtututor.png",
      title: "Tututor.Ai",
      desc: "AI-powered educational platform serving 20+ schools and 1,500+ teachers across Spain, automating lesson planning and reducing content creation time by 95%.",
      fullDescription: "Tututor.Ai is a comprehensive AI platform that revolutionizes education by helping Spanish teachers save weeks of preparation time. Built from the ground up with cutting-edge AI technology, it serves as a complete educational ecosystem with tools that teachers use daily for lesson planning, assessment, and student engagement.",
      link: "https://tututor.vercel.app/",
      category: ["React Js", "Tailwind", "Html"],
      features: [
        "Custom AI Chatbots - Teachers create topic-specific tutors and track student conversations",
        "Smart Quiz Generator - AI creates and auto-grades quizzes with real-time analytics",
        "Lesson Planning Suite - Automated unit creation aligned with Spanish curriculum",
        "Multimodal AI - Text-to-speech with ElevenLabs, image generation with multiple LLMs",
        "Assessment Tools - Rubric generation, exam creation, and performance tracking",
        "Learning Resources - Mind maps, summaries, vocabulary lists, and study guides"
      ],
      technologies: [
        "React.js & Next.js",
        "Node.js & Express.js",
        "MongoDB",
        "Tailwind CSS",
        "Multiple LLMs (GPT-4, Claude, Gemini)",
        "ElevenLabs API",
        "DALL-E & Stable Diffusion",
        "Stripe Payments",
        "Microservices Architecture"
      ],
      metrics: [
        "Serves 20+ schools actively",
        "1,500+ registered teachers",
        "Handles 8K+ concurrent users",
        "95% reduction in content creation time",
        "99.9% platform uptime",
        "Teachers save 7+ hours weekly"
      ],
      highlights: [
        "Lead Developer position",
        "Built from scratch (Nov 2023 - Present)",
        "Adapted to Spanish regional curricula (17 autonomous communities)",
        "Integrated multiple AI models for diverse use cases",
        "Real-time performance analytics dashboard",
        "Responsive design for all devices"
      ],
      role: "Lead Developer",
      duration: "Nov 2023 - Present",
      impact: "Reduced teacher planning time from 7.5 hours to 1.25 hours per week, helping educators focus on actual teaching rather than administrative tasks."
    },
    // {
    //   src: "./images/fiindustries.png",
    //   title: "Fi Industries",
    //   desc: "On Fi Industries, users can get fiber-glass products at low prices.",
    //   link: "https://fiindustries.org/",
    //   category: ["Html"],
    // },
    {
      src: "./images/insight-x.png",
      title: "Insight-X",
      desc: "Revolutionary AI-powered business intelligence platform that automatically generates custom analytics functions, helping MedSpa owners grow revenue and streamline operations through data-driven insights.",
      fullDescription: "Insight-X is a groundbreaking business intelligence platform built with an innovative approach: using AI to automatically generate JavaScript analytics functions based on any input data. The platform revolutionizes how MedSpas analyze their business by adapting to different data structures and creating tailored insights without manual coding or the need for analysts.",
      link: "https://www.insight-x.io/",
      category: ["React Js", "Tailwind"],
      features: [
        "Real-Time Dashboards - Track revenue, bookings, and rebook rates in one unified place",
        "Service & Provider Analytics - Monitor treatment margins and individual provider performance",
        "AI-Powered Strategy Reports - Receive personalized, data-driven business recommendations",
        "Smart Booking Optimization - AI identifies open slots and suggests strategies to fill them",
        "Revenue Intelligence - Automated analysis to increase revenue per treatment",
        "Client Retention Insights - Track and improve client rebooking rates",
        "Retail Revenue Growth - Data-driven recommendations for increasing retail sales",
        "Multi-Platform Integration - Connects with Boulevard, Zenoti, Vagaro, and major MedSpa tools",
        "Zero-Setup Analytics - Automatic data cleaning, analysis, and visualization",
        "Weekly Business Reports - Actionable steps delivered automatically"
      ],
      technologies: [
        "React.js",
        "Tailwind CSS",
        "AI/ML Models",
        "JavaScript Code Generation",
        "Data Visualization Libraries",
        "RESTful APIs",
        "Third-party Integrations",
        "Real-time Data Processing",
        "Cloud Infrastructure"
      ],
      metrics: [
        "Helped client secure $250K funding",
        "Zero manual coding required",
        "Minutes to setup and deploy",
        "Real-time data processing",
        "Multi-platform compatibility"
      ],
      highlights: [
        "Innovative AI approach to generate custom analytics code automatically",
        "Built specifically for MedSpa industry needs",
        "No technical expertise required for end users",
        "Adapts to any data structure dynamically",
        "Platform resulted in successful $250K funding round",
        "Eliminates need for data analysts or consultants",
        "Automated weekly insights and recommendations",
        "Seamless integration with popular MedSpa software"
      ],
      role: "Full-Stack Developer",
      duration: "Dec 2024 - Jun 2025",
      impact: "Created an innovative AI-driven analytics platform that automatically generates custom JavaScript analytics functions from any business data, eliminating the need for manual coding or hiring analysts. This unique approach helped the client secure $250K in funding."
    },
    {
      src: "./images/viloi.png",
      title: "Viloi",
      desc: "Advanced AI humanization platform with stunning modern UI featuring glassmorphism, animated backgrounds, and smooth micro-interactions. Helps users create undetectable AI content that bypasses all major AI detection tools.",
      fullDescription: "Viloi is a cutting-edge AI platform that transforms AI-generated content into human-like text, featuring the Vivi and Vivi Pro AI assistants. Built with a focus on both functionality and aesthetics, the platform combines powerful AI humanization technology with a visually stunning interface featuring glassmorphism effects, animated backgrounds, and seamless user interactions.",
      link: "https://viloi.com/",
      category: ["React Js", "Tailwind", "Css"],
      features: [
        "AI Text Humanizer - Transforms AI content into undetectable human-like writing",
        "Multiple AI Detection Bypass - Passes Turnitin, GPTZero, Originality.ai, Copyleaks, ZeroGPT",
        "Vivi AI Assistant - Dual versions (Vivi & Vivi Pro) for different user needs",
        "Smart Research Tools - Web search, PDF analysis, and complex problem solving",
        "AI Score Detection - Real-time AI content detection percentage display",
        "Citation & Attachment System - Academic citation support and file attachments",
        "Code Optimization - Refactor and debug code with AI assistance",
        "Canvas Feature - Visual algorithm representation for developers",
        "Plagiarism Shield - Protects content from academic integrity flags",
        "Math Problem Solver - Step-by-step solutions for complex calculations",
        "Turnitin Checks - Integrated verification system (60 checks in Pro plan)",
        "Stripe Payment Integration - Seamless subscription management"
      ],
      technologies: [
        "React.js",
        "Tailwind CSS",
        "Custom CSS (Glassmorphism)",
        "Framer Motion / Anime.js",
        "Multiple LLM Integration",
        "Stripe Payments API",
        "AI Detection APIs",
        "Real-time Processing",
        "Responsive Design",
        "Advanced Animations"
      ],
      metrics: [
        "0% AI detection score achieved",
        "Bypasses 7+ major AI detectors",
        "100% human-like content rating",
        "Dual AI assistant versions",
        "Free trial with unlimited Pro plan option",
        "Pixel-perfect responsive design"
      ],
      highlights: [
        "Stunning modern UI with glassmorphism design system",
        "Smooth micro-interactions and animated backgrounds",
        "Integrated multiple LLMs for content humanization",
        "Full Stripe payment implementation",
        "Responsive design across all devices",
        "Advanced CSS animations and effects",
        "Real-time AI detection scoring",
        "Comprehensive subscription system with free and Pro tiers",
        "Built-in Turnitin verification checks",
        "Multi-purpose AI assistant (coding, math, research, writing)"
      ],
      role: "Frontend Developer",
      duration: "Mar 2024 - Jun 2024",
      impact: "Built a visually stunning AI humanization platform featuring advanced glassmorphism UI, animated interactions, and integrated multiple LLMs to convert AI text into undetectable content. Implemented complete Stripe payment system for subscription management, delivering pixel-perfect responsive design that seamlessly works across all devices."
    },
    {
      src: "./images/jurri.png",
      title: "Jurri Drive | Mail",
      desc: "All-in-one e-management platform combining cloud storage (like Google Drive), multi-email management, and password management. Features drag-and-drop uploads, dynamic folder structures, and robust security measures for complete digital workspace organization.",
      fullDescription: "Jurri is a comprehensive digital workspace platform that combines three essential productivity tools into one seamless experience: cloud storage, email management, and password security. Built to streamline daily workflows, it offers Google Drive-like file management with advanced features including drag-and-drop uploads, dynamic folder organization, multi-email account management, and enterprise-grade password protection with encryption and cross-device synchronization.",
      link: "https://jurri.danzeetech.com/login",
      category: ["React Js", "Tailwind"],
      features: [
        "Cloud Storage System - Secure file storage accessible anytime, anywhere",
        "Drag-and-Drop File Uploads - Intuitive file upload with visual feedback",
        "Dynamic Folder Structure - Create, organize, and manage custom folder hierarchies",
        "Multi-Email Manager - Manage multiple email accounts from single dashboard",
        "Password Manager - Robust encryption for secure credential storage",
        "Cross-Device Synchronization - Seamless access across all devices",
        "User Authentication System - Secure login and signup with session management",
        "File Preview & Management - View, download, and organize files efficiently",
        "Search Functionality - Quick file and email search across platform",
        "Reusable Component Architecture - Built with modular, maintainable code",
        "Custom Hooks - Optimized React hooks for complex state management",
        "Error Handling System - Robust error management throughout application"
      ],
      technologies: [
        "React.js",
        "Tailwind CSS",
        "Custom React Hooks",
        "Reusable Components",
        "File Upload APIs",
        "Encryption Libraries",
        "RESTful API Integration",
        "Authentication System",
        "State Management",
        "Drag-and-Drop Libraries",
        "Form Validation",
        "Responsive Design"
      ],
      metrics: [
        "3-in-1 platform integration",
        "Google Drive-like functionality",
        "Multi-email management",
        "Secure password encryption",
        "Cross-device compatibility",
        "Highly optimized codebase"
      ],
      highlights: [
        "Built comprehensive all-in-one productivity platform",
        "Implemented Google Drive-like cloud storage system",
        "Drag-and-drop file upload with real-time feedback",
        "Dynamic folder creation and management system",
        "Multi-email account management interface",
        "Secure password manager with encryption",
        "Cross-device synchronization capabilities",
        "Developed extensive library of reusable components",
        "Created custom React hooks for complex functionality",
        "Implemented robust error handling throughout",
        "Highly optimized code for performance",
        "Complete authentication and authorization system",
        "Responsive design for desktop and mobile use"
      ],
      role: "Frontend Developer",
      duration: "Sep 2023 - Apr 2024",
      impact: "Worked as Frontend Developer on an all-in-one e-management platform combining cloud storage, multi-email management, and password security. Developed Google Drive-like functionality with drag-and-drop uploads and dynamic folder structures. Built extensive reusable component library, custom hooks, and ensured robust error handling with highly optimized code for a seamless user experience across all features."
    },
    {
      src: "./images/yaksport.png",
      title: "Yaksport",
      desc: "Comprehensive sports training camp booking platform built for Danish travel agency, featuring advanced filtering, multi-language support (Danish/English), and interactive galleries serving hundreds of sports clubs.",
      fullDescription: "Yaksport is a specialized travel booking platform designed for Danish sports clubs, associations, and schools planning training camps abroad. Built for a Danish travel agency with over 15 years of experience, the platform streamlines the entire booking process from search to reservation, offering comprehensive travel planning tools tailored specifically for sports teams.",
      link: "https://yaksport.com/",
      category: ["React Js", "Tailwind"],
      features: [
        "Advanced Search & Filtering - Filter by country, sport type, dates, and airport",
        "Multi-Language Support - Full Danish and English translations via I18next",
        "Interactive Hotel Galleries - Browse accommodations with rich image galleries",
        "Custom Quote System - Request personalized travel packages for teams",
        "FAQ Management - Comprehensive information about travel, visas, insurance",
        "Blog Integration - Travel tips and destination guides",
        "Responsive Booking Interface - Seamless experience across all devices",
        "Date Range Picker - Flexible trip duration selection",
        "Sport-Specific Categories - Tailored options for different sports",
        "Group Travel Management - Special features for team bookings",
        "Customer Testimonials - Social proof with rebooking statistics",
        "Contact & Support System - Easy communication with travel agents"
      ],
      technologies: [
        "React.js",
        "Tailwind CSS",
        "I18next (Multi-language)",
        "React Router",
        "Date Picker Libraries",
        "Responsive Design",
        "RESTful API Integration",
        "Form Validation",
        "Image Optimization",
        "SEO Best Practices"
      ],
      metrics: [
        "Serves hundreds of sports clubs",
        "15+ years agency experience",
        "Multi-language platform (DA/EN)",
        "Comprehensive travel information",
        "High customer rebooking rate",
        "Fully responsive design"
      ],
      highlights: [
        "Built for established Danish travel agency specializing in sports training camps",
        "Comprehensive multi-language implementation using I18next",
        "Advanced filtering system for countries, sports, dates, and airports",
        "Interactive image galleries for hotel browsing",
        "Specialized features for group travel and team management",
        "Integrated blog system for travel content",
        "Custom quote request functionality",
        "Extensive FAQ system covering visas, insurance, baggage, and more",
        "Responsive design optimized for mobile and desktop",
        "SEO-optimized for Danish market"
      ],
      role: "Frontend Developer",
      duration: "Jan 2023 - Jan 2024",
      impact: "Created a comprehensive sports training camp booking platform for a Danish travel agency, implementing advanced filtering, multi-language support, and interactive galleries. The responsive React frontend serves hundreds of sports clubs and provides a seamless booking experience across all devices."
    },
    {
      src: "./images/enomad.png",
      title: "E-Nomad Tax",
      desc: "Modern, mobile-first website for global business expansion consultancy, helping freelancers and entrepreneurs minimize taxes through offshore company formation, international banking, and strategic residency planning.",
      fullDescription: "E-Nomad Tax is a comprehensive platform for VEGG CONSULTING LTD, a third-generation family business specializing in offshore solutions. With 7+ years of experience and serving 5,000+ clients globally, the platform streamlines the complex process of international business formation, banking access, and tax optimization for entrepreneurs operating across borders.",
      link: "https://www.enomadtax.com/",
      category: ["React Js", "Tailwind"],
      features: [
        "Strategic Company Setup - Complete offshore company formation and registration services",
        "Banking Solutions Access - Tailored international banking connections and support",
        "Compliance & Risk Advisory - Expert guidance through complex regulations",
        "Asset Protection Services - Secure wealth management and protection strategies",
        "Payment Gateway Integration - Secure, efficient global payment solutions",
        "Interactive Questionnaire - Smart matching system for optimal jurisdiction selection",
        "Blog & Resource Center - Educational content on offshore business and taxation",
        "Consultation Booking System - Easy calendar integration for client meetings",
        "Mobile-First Design - Optimized responsive experience across all devices",
        "Service Showcase - Clear presentation of 5+ core service offerings",
        "FAQ System - Comprehensive answers to offshore formation questions",
        "Multi-Page Architecture - About, Services, Pricing, Blogs, Contact sections"
      ],
      technologies: [
        "React.js",
        "Tailwind CSS",
        "Modern CSS Animations",
        "Responsive Design",
        "React Router",
        "Form Handling",
        "API Integration",
        "SEO Optimization",
        "Performance Optimization",
        "Mobile-First Development"
      ],
      metrics: [
        "7+ years of experience",
        "5,000+ clients served",
        "500+ positive reviews",
        "10+ service offerings",
        "Third-generation family business",
        "Global market presence"
      ],
      highlights: [
        "Designed for established consulting firm (VEGG CONSULTING LTD)",
        "Modern, clean interface with professional corporate design",
        "Mobile-first responsive development approach",
        "Strategic content organization across multiple pages",
        "Interactive questionnaire for personalized jurisdiction matching",
        "Comprehensive service presentation system",
        "Educational blog integration for SEO and client education",
        "Clear call-to-actions throughout user journey",
        "Professional typography and spacing",
        "Optimized for conversion and lead generation",
        "Fast load times and smooth animations",
        "Built to communicate complex offshore services clearly"
      ],
      role: "UI/UX Developer",
      duration: "May 2025 - Aug 2025",
      impact: "Designed and developed a modern, mobile-first website for an established global business consultancy serving 5,000+ clients. Created a clean, professional interface that clearly communicates complex offshore services, featuring an interactive jurisdiction matching system and comprehensive resource center to convert visitors and educate potential clients."
    },
    {
      src: "./images/crownkabab.png",
      title: "Crown Kabab",
      desc: "Full-featured e-commerce food ordering platform for Danish takeaway restaurant, featuring Redux Toolkit state management, integrated payment gateway, Google OAuth authentication, and complete multi-language support.",
      fullDescription: "Crown Kabab is a comprehensive online food ordering system built for a Danish takeaway restaurant. The platform provides customers with a seamless ordering experience, from browsing the menu to secure checkout, with support for multiple languages to serve Denmark's diverse population. Built with modern React architecture and Redux Toolkit for robust state management.",
      link: "https://crownkebab.dk/",
      category: ["React Js", "Tailwind"],
      features: [
        "Online Food Ordering - Complete e-commerce system for takeaway orders",
        "Redux Toolkit State Management - Efficient global state with RTK Query for API calls",
        "Secure Payment Gateway - Integrated payment processing for online transactions",
        "Google OAuth Integration - Social login for quick customer authentication",
        "Shopping Cart System - Add, remove, and manage items with real-time updates",
        "Wishlist Functionality - Save favorite menu items for future orders",
        "Multi-Language Support - I18next integration for Danish and other languages",
        "Menu Browsing - Organized categorized food menu with images and descriptions",
        "Order Management - Track order status and history",
        "Responsive Design - Optimized experience across mobile, tablet, and desktop",
        "User Account System - Customer profiles with order history",
        "Real-Time Price Calculations - Dynamic pricing with cart updates"
      ],
      technologies: [
        "React.js",
        "Redux Toolkit",
        "RTK Query",
        "Tailwind CSS",
        "I18next (Multi-language)",
        "Google OAuth API",
        "Payment Gateway API",
        "React Router",
        "Form Validation",
        "Responsive Design",
        "RESTful API Integration",
        "Local Storage Management"
      ],
      metrics: [
        "Full e-commerce functionality",
        "Multi-language platform",
        "Secure payment integration",
        "Google OAuth authentication",
        "Real-time cart management",
        "Complete order system"
      ],
      highlights: [
        "Built complete e-commerce solution for Danish restaurant",
        "Implemented Redux Toolkit for scalable state management",
        "Integrated RTK Query for efficient API data fetching and caching",
        "Secure payment gateway implementation for online transactions",
        "Google OAuth integration for seamless user authentication",
        "Shopping cart with real-time updates and calculations",
        "Wishlist feature for customer convenience",
        "Multi-language support using I18next (Danish and additional languages)",
        "Fully responsive design across all devices",
        "Optimized performance for fast page loads",
        "User account system with order tracking",
        "Production-ready e-commerce platform serving real customers"
      ],
      role: "Frontend Developer",
      duration: "Nov 2022 - May 2023",
      impact: "Developed a comprehensive React.js e-commerce platform with Redux Toolkit/RTK Query for state management and API integration. Implemented secure payment gateway, Google OAuth authentication, full shopping cart and wishlist features, and multi-language support via I18next. Delivered a responsive, performant food ordering experience across all devices for a live Danish restaurant."
    },
  ];